from enum import Enum


class ErrorCode(str, Enum):
    INVALID_REQUEST = "AI_INVALID_REQUEST"
    UPSTREAM_AUTH_ERROR = "AI_UPSTREAM_AUTH_ERROR"
    MODEL_NOT_FOUND = "AI_MODEL_NOT_FOUND"
    CONTENT_REJECTED = "AI_CONTENT_REJECTED"
    UPSTREAM_RATE_LIMIT = "AI_UPSTREAM_RATE_LIMIT"
    UPSTREAM_TIMEOUT = "AI_UPSTREAM_TIMEOUT"
    UPSTREAM_UNAVAILABLE = "AI_UPSTREAM_UNAVAILABLE"
    RESPONSE_FORMAT_ERROR = "AI_RESPONSE_FORMAT_ERROR"
    STREAM_INTERRUPTED = "AI_STREAM_INTERRUPTED"
    UNAUTHORIZED = "AI_UNAUTHORIZED"
    INTERNAL_ERROR = "AI_INTERNAL_ERROR"
